name: Publish to GH Pages
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - run: npm install

    - run: npm run build

    - name: Push on Pinata
      id: ipfs
      if: success()
      uses: aquiladev/ipfs-action@v0.1.5
      with:
        path: ./dist
        service: pinata
        pinataKey: ${{ secrets.API_KEY }}
        pinataSecret: ${{ secrets.API_SECRET }}
    
    - name: Pin on personal IPFS node
      if: success()
      continue-on-error: true
      run: curl --silent --user ${{ secrets.ipfs_user }}:${{ secrets.ipfs_password }} -X POST https://api.ipfs.ccr.ydns.eu/api/v0/pin/add\?arg\=${{ steps.ipfs.outputs.hash }}\&key\=blog
    
    - name: Update DNS with new IPFS hash
      if: success()
      env:
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
        RECORD_DOMAIN: 'aciceri.dev'
        RECORD_NAME: '_dnslink.cv'
        CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      uses: textileio/cloudflare-update-dnslink@0fe7b7a1ffc865db3a4da9773f0f987447ad5848
      with:
        cid: ${{ steps.ipfs.outputs.hash }}

    - name: Deploy on Github Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: dist/
        fqdn: cv.aciceri.dev
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
